### ISSUE TITLE
Add migration guides 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-api#106]
#### Reason/Context
Currently, we have no docs that describe the migration guide between versions, we should add them.

This can be done by checking the commit history and looking for commits with `!:` i.e. `feat!:`, that describes a breaking change.

**Comment by jonaslagoni** [comment]
Here is the TLDR:

## Message

```diff
- - messageId(): `string` | `undefined`
- - schemaFormat(): `string`
+ - schemaFormat(): `string` | `undefined`
```

## MessageTrait

```diff
- - messageId(): `string` | `undefined`
- - schemaFormat(): `string`
+ - schemaFormat(): `string` | `undefined`
```


for `messageId` use `id` instead.

**Comment by Ibukun-tech** [comment]
what is the meaning of TLDR?

**Comment by jonaslagoni** [comment]
It's just the short answer to the changes that were between the two versions of v2 and v3 of the parser.

`messageId` got removed, and should use `id` instead, `schemaFormat` changed return types.

**Comment by Ibukun-tech** [comment]
can I be assigned to this

**Comment by Ibukun-tech** [comment]
@jonaslagoni

**Comment by jonaslagoni** [comment]
We got no assignments, just say you are working on it and that's it 👍

**Comment by Ibukun-tech** [comment]
I am working on this

**Comment by Ibukun-tech** [comment]
can this be changed to hasMessageId() to hasId()

**Comment by RegretfulWinter** [comment]
Hi @jonaslagoni, I'm Jiehui, a newcomer to AsyncAPI community. I came across this good first issue and based on the TLDR I made a draft version of the migration guide specially for Parser in this [PR](https://github.com/asyncapi/parser-api/pull/107). Looking forward to any feedback on the wording or if there are anything incorrect please let me know.

Also, I am not sure if creating the migration document inside this repository is the ideal practice. Shall we integrate it into the [main migration guide](https://github.com/asyncapi/website/blob/d3d4af63e0506f83a2b5087bbbabbb31a34d4b8a/pages/docs/migration/migrating-to-v3.md)?

cc @Ibukun-tech also open to discussion so that we can work on together to make the document better!

**Comment by Ibukun-tech** [comment]
@RegretfulWinter  lets work on this together
